# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "update to appstore"
  lane :update_app_store do
  	  increment_build_number
	gym(
		scheme:"text",
        export_method:"app-store",
		output_directory:"./fastlane/build",
		archive_path:"./Archive",
		clean:"ture",
		# codesigning_identity:"emule_distribution",
	)	
	deliver
  end
end
